services:
  - type: web
    name: nodejs-backend
    env: node
    plan: free
    branch: main
    buildCommand: "npm install"
    startCommand: "npm run start"
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        value: MONGODB_URI # Add your MongoDB Atlas URI here
      - key: PORT
        value: "5000"  # Default port Render uses for web services is 10000, but you can specify a different one if needed
